# 2020-09-29 10:04:22 -0400 - Jeremy Axmacher - Add automatic deploy - lines:,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29
# 2020-09-29 13:18:58 -0400 - Jeremy Axmacher - Add issue creation for deployment failure - lines:,25
name: Deploy latest from master branch
on:
  push:
    branches: [master]

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: ${{ secrets.INSTANCE_ID }}

          working-directory: /home/ssm-user
          command: /bin/sh ./wrapper.sh

      # Catch SSM outputs
      - name: Get output
        run: echo "The Command id is ${{ steps.ssm.outputs.command-id }}"
